### ISSUE TITLE
Feature requests / TODO

### ISSUE THREAD

**Issue by lehner** [lehner/gpt#1]
This is a collection of current feature requests / TODO items

**Comment by daknuett** [comment]
Generating documentation (various output formats; particularely HTML) can be done using [sphinx](https://www.sphinx-doc.org/en/master/). 

The generated HTML documentation can be hosted on [GitHub Pages](https://pages.github.com/);
[this Makefile](https://gist.github.com/daknuett/5af9f127949732ea775879e1c6f45070) makes exporting the sphinx HTML site to GitHub Pages easy.

**Comment by lehner** [comment]
* Requests / Ideas (Milestones highlighted):
  * **BENCHMARKS both single node and multi-node start with QP3**
  * Count flops of expression and allow to show FLOP/s
  * Grid's optimized Wilson operator / solvers
  * DWF
  * Continuous Integration / Tests (maybe copy Grid strategy with local server? [Max])
  * Documentation in Python style
  * Text files for parameters (could later include inline-python statements to evaluate)
  * For IO make parallel number of reader nodes configurable
  * Fermion/Gauge classes that take parameters but have solvers etc. already defined
  * **Baryons/Meson (standard measurement package, 2pt mesons/baryons, 3pt)**
  * Smearing
  * HDF5 output / benchmarking different implementations (Python/C++)
  * IRLanc, Multi-Grid methods (IRL + other solvers)
  * A2A (Locally coherent)
  * Sparse field support
  * Distillation
  * Open BC / SF
  * Quadruple precision global sums
  * **Compressed eigenvector IO for general action + Local Coherent IRL**
  * HMC / Ensemble generation / AI methods
  * LICENSE BSD2 / GPL? Stefan has input!
  * Grid fork as basis, need (frequent) merging upstream!
  
* How to proceed:
  * Regular meetings to discuss (Meeting every two weeks remotely)
     Friday 1pm starting March 27 using teleconf.
  * Who wants to continue to participate in discussions / coding? -> local TODO file

**Comment by lehner** [comment]
I have merged the feature requests to the slack channel and will close this issue.
