### ISSUE TITLE
Tests failing for Intel ICX due to default fp-model=fast

### ISSUE THREAD

**Issue by pjgeorg** [lehner/gpt#123]
The Intel compiler icx (icpx for C++) uses `-fp-model=fast` by default. The same probably also applies to the Intel C/C++ Compiler Classic, but these have not been tested.
One of the tests of `core/tensors.py` fails due to this option. In particular this line:
`assert g.norm2(ms[0, 0, 0, 0] - g.color_trace(msc[0, 0, 0, 0])) < 1e-13`
The value using icx is `1.7585932263541338e-13`

I currently see two options to fix this issue (and hence have not opened a PR):
1. Leave the test as is and try to get a patch upstream in Grid to add `-fp-model=precise` for all Intel compilers.
2. Change the test to be a little more imprecise, e.g., set the tolerance to 1e-12.

Disadvantages of the second option are that similar changes might also be required to be applied to other checks. And people who are not aware of the lax Intel compiler defaults might run into unexpected results.

Note that even with `-fp-model=precise` there might be differences between available compilers due to the differing defaults for `-ffp-contract`.

**Comment by lehner** [comment]
Let us force the -fp-model=precise in Grid's configure.
