### ISSUE TITLE
g.ml has no attribute 'network'

### ISSUE THREAD

**Issue by Cynog** [lehner/gpt#128]
I just tested GPT using docker. The notebook 05_ml_first_look in the tutorials folder yields the following error.

![Screenshot from 2023-04-25 13-55-25](https://user-images.githubusercontent.com/58817236/234268929-dfabbff4-9559-4b4e-a711-e636a5da9909.png)

**Comment by lehner** [comment]
Thanks for pointing this out.  There was a change in naming convention that was not reflected in the notebook.  I fixed it in commit fc67011 .
