### ISSUE TITLE
Gauge-equivariant neural networks as preconditioners in lattice QCD

### ISSUE THREAD

**Issue by tanwimallick** [lehner/gpt#130]
Hi,

I am trying to run the code referred to in the paper but am facing two issues in the following code:

# define a coarse grid
coarse_grid = g. grid ([4 ,4 ,4 ,4] , g . double )

# load \ bar {u}_i vectors
u_bar = g. load (" u_bar ")

# create a blocking map
b = g. block. map ( coarse_grid , basis )

Not sure from where I can load **u_bar** and how to define the **basis**

Can you please help me.

Thanks,
Tanwi

**Comment by lehner** [comment]
Dear Tanwi,

the following code could create the needed fields for an example case.  In fact there is a typo in arXiv v1, the basis variable
should also be called u_bar:

```python3
#!/usr/bin/env python3
import gpt as g
import sys

L = [8,8,8,16]
ncoarse=12

for conf in ["data/gauge_configuration"]:

    rng = g.random("d")
    grid = g.grid(L, g.double)

    coarse_grid = g.grid([2,2,2,4], g.double)

    U = g.load(conf)

    Q = g.qcd.fermion.wilson_clover(
        U,
        {
            "mass": -0.6,
            "csw_r": 1,
            "csw_t": 1,
            "xi_0": 1,
            "nu": 1,
            "isAnisotropic": True,
            "boundary_phases": [1.0, 1.0, 1.0, 1.0], # for now only periodic allowed since PT uses periodic!
        },
    )

    inv = g.algorithms.inverter
    fgmres = inv.fgmres({"eps": 1e-7, "maxiter": 20000, "restartlen": 20})
    inv0 = fgmres(Q)

    basis=[rng.normal(g.vspincolor(grid)) for i in range(ncoarse)]
    zero=g.lattice(basis[0])
    zero[:]=0
    for b in basis:
        inv0(b,zero)

    # created near null space here explicitly, later learn it
    b = g.block.map(coarse_grid, basis)
    b.orthonormalize()
    b.orthonormalize()

    g.save("u_bar", basis)
```

**Comment by lehner** [comment]
The "data/gauge_configuration" file btw. could be created by the heatbath algorithm demonstrated in https://github.com/lehner/gpt/blob/master/tests/markov/pure_gauge.py

**Comment by tanwimallick** [comment]
Thank you for getting back to me. I looked at the https://github.com/lehner/gpt/blob/master/tests/markov/pure_gauge.py code to generate "data/gauge_configuration". Should I save markov for that? I'm sorry, I'm actually pretty new to this field and code.

**Comment by lehner** [comment]
No worries.  It is an SU(3) gauge configuration for the fields U_\mu for which the operator is defined.  One would need a thermalized (in the sense of the Markov process) gauge configuration for \beta=6.0 to re-produce the results of the paper.  The linked script with appropriate parameters would generate such a Markov chain.  If you just interested in playing with the network architecture but not so much in the QCD background, I would be happy to share the gauge configuration we used in the paper with you.  If so, just reach out to on my university email address that is given in the arXiv paper.

**Comment by tanwimallick** [comment]
I sent you an email yesterday
