### ISSUE TITLE
gpt.core.expr.factor appears to be dead/unused

### ISSUE THREAD

**Issue by daknuett** [lehner/gpt#145]
When applying
```
diff --git a/lib/gpt/core/expr.py b/lib/gpt/core/expr.py
index 263380c6..205d567e 100644
--- a/lib/gpt/core/expr.py
+++ b/lib/gpt/core/expr.py
@@ -177,6 +177,9 @@ class expr:
 
 
 class factor:
+    def __init__(self):
+        gpt.message("factor created")
+        raise Exception("STOP for testing")
     def __rmul__(self, l):
         return expr(l) * expr(self)
 
```

All tests pass. Also, `grep`ing for `factor()` does not yield any results. 

It appears that this class can be removed.

**Comment by lehner** [comment]
It is used as a base class, explaining why your grep of "factor()" was not successful.  Look for example at https://github.com/lehner/gpt/blob/master/lib/gpt/core/operator/matrix_operator.py .
