### ISSUE TITLE
Setup problems with openmpi 4.0.3

### ISSUE THREAD

**Issue by aragon999** [lehner/gpt#4]
When I compile against the latest Grid version from your Grid branch (currently https://github.com/lehner/Grid/commit/856d168e4131b915ecab245753b44b690662c881) with the following configure flags:
```
CC=clang CXX=clang++ CXXFLAGS=-fPIC ../configure --enable-precision=double \
                                      --enable-simd=AVX2 \
                                      --enable-comms=mpi-auto \
                                      --prefix=/usr
```
I get the following error when I import `cgpt`:
```
python
Python 3.8.2 (default, Feb 26 2020, 22:21:03) 
[GCC 9.2.1 20200130] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cgpt
*** The MPI_Comm_rank() function was called before MPI_INIT was invoked.
*** This is disallowed by the MPI standard.
*** Your MPI job will now abort.
[max-desktop:10792] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```
I used `openmpi 4.0.3` on ArchLinux and `clang 9.0.1`.

If I can be of further assistance let me know :-)

**Comment by lehner** [comment]
This problem is likely related to the other segfault problem and is fixed for me on kern-login-001 in Stefan's setup by commit 890a3f64d04fe1154f72fbfd3e9d64054de7d79f .  Please confirm.

**Comment by aragon999** [comment]
I can confirm that this commit fixes the issue for me, thank you.
