### ISSUE TITLE
Autotools build enables compiling with debugging information

### ISSUE THREAD

**Issue by pjgeorg** [lehner/gpt#45]
The current autotools setup seems to compile cgpt with debugging information enabled (-g).
Is this done on purpose / known?
I was unable to locate where it is enabled. I suspect libtool adds this compiler flag.

This might explain why cgpt.so is so heavy by now. In my case it is now 2.4GB.

**Comment by lehner** [comment]
I see no reason to keep -g for autotools.  Your file size is surprising given the artifacts including cgpt.so are O(100MB), e.g., in https://github.com/lehner/gpt/actions/runs/178999678 .

**Comment by pjgeorg** [comment]
> Your file size is surprising given the artifacts including cgpt.so are O(100MB), e.g., in https://github.com/lehner/gpt/actions/runs/178999678 .

These artifacts are compressed with zip in addition to the deb files being compressed using xz.
E.g. python-gpt-Linux-python-3.6-gcc-none-0.0.0rb0659d7.zip is 141MB, the included cgtp.so is 1.4GB.

Which is, surprisingly, still ~1GB smaller than what I get.

Using xz compression I get down to 200-250MB.
