### ISSUE TITLE
[autotools] The compiler from grid-config seems to be ignored

### ISSUE THREAD

**Issue by aragon999** [lehner/gpt#54]
I think this it could be an autotools related issue, not really sure, since I cannot see any problem in the `configure.ac`.

But currently I think not the compiler from `grid-config` is used but the one specified in the environment variables CC/CXX is used, see for example the Github actions:
https://github.com/lehner/gpt/runs/1013791173#step:17:74

I also started to debug, see here ([where I print the path of the Grid compiler and the version](https://github.com/aragon999/gpt/blob/b8e559de699b60f6387cd4335052d36b1002fec5/.github/workflows/github-build-test.yml#L231-L234)):
https://github.com/aragon999/gpt/runs/1014245867?check_suite_focus=true#step:11:83

This issue is not really pressing I think, since normally the environment variables should be correctly set (especially when working with a module system).

**Comment by pjgeorg** [comment]
Have just been hit by this bug as well trying to fix the x86/cuda RQCD CI.

grid-config --cxx reports "nvcc -x cu".
Any idea how to fix this without requiring to setting CXX to the correct value manually?

**Comment by aragon999** [comment]
I looked at the `configure.ac` in more detail, and noticed the following code (and comments):
https://github.com/lehner/gpt/blob/master/configure.ac#L143-L148

So apparently if one sets the environment variables, they will be used, no matter what the output of `grid-config` is.

Probably this is necessary to be able to specify the compiler, independently of the `grid-config`.

**Comment by DanielRichtmann** [comment]
> I looked at the `configure.ac` in more detail, and noticed the following code (and comments):
> https://github.com/lehner/gpt/blob/master/configure.ac#L143-L148
> 
> So apparently if one sets the environment variables, they will be used, no matter what the output of `grid-config` is.
> 
> Probably this is necessary to be able to specify the compiler, independently of the `grid-config`.

This may be nice to have, but I can't come up with a sensible use case where one would like to use different compilers for the two libraries.
Anyway the behavior is still incorrect and should be fixed. Maybe @ssolbUR knows more about this?

**Comment by pjgeorg** [comment]
> I looked at the `configure.ac` in more detail, and noticed the following code (and comments):
> https://github.com/lehner/gpt/blob/master/configure.ac#L143-L148
> 
> So apparently if one sets the environment variables, they will be used, no matter what the output of `grid-config` is.

This makes sense. However, in my case CXX was NOT set. autotools still ignored the output of grid-config --cxx and just set the compiler to g++.

Turns out AC_PROG_CXX, which is used [here](https://github.com/lehner/gpt/blob/63ad008c58a034d5ce31fab8be3f3a4b0fc8709e/configure.ac#L29), sets the CXX environment variable (defaulting to g++). Hence the lines you referred to always set CXX to the compiler selected by AC_PROG_CXX and never use the compiler used to compile grid.

**Comment by ssolbUR** [comment]
Hi,

I think the problems are these lines (by me)
They are are a way to set default. I put them in before we had the AC_PROG_CXX in configure.ac
the syntax

: ${foo:=bar}  

Will set  foo=bar  only if foo is undefined. So it's useful to set default values.
So either remove AC_PROG_CXX (might have other side effects) or change these lines:

: ${GRID_CXXLD:=${GRID_CXX}}
: ${CXX:=${GRID_CXX}}
: ${CXXLD:=${GRID_CXXLD}}

probably to 

: ${GRID_CXXLD:=${GRID_CXX}}
CXX="${GRID_CXX}"
CXXLD="${GRID_CXXLD}"

best wishes,
Stefan

-- 
Dr. Stefan Solbrig
Universität Regensburg, Fakultät für Physik,
93040 Regensburg, Germany
Tel +49-941-943-2097

**Comment by pjgeorg** [comment]
@ssolbUR Proposed fix #71 should be fine as well? This way we still allow the user to overwrite the compiler, but not AC_PROG_CXX.

**Comment by lehner** [comment]
Noch longer relevant, will move away from autotools
