### ISSUE TITLE
[autotools] Bad mangling of CXXFLAGS

### ISSUE THREAD

**Issue by pjgeorg** [lehner/gpt#72]
autotools destroys proper CXXFLAGS for compilers like nvcc (-Xcompiler).
E.g. when grid-config --cxxflags outputs:
`-O3 -ccbin g++ -gencode arch=compute_75,code=sm_75 -Xcompiler -fPIC -Xcompiler -fno-strict-aliasing --expt-extended-lambda --expt-relaxed-constexpr -Xcompiler -fopenmp`

autotools changes this to:
`-O3 -ccbin g++ -gencode -Xcompiler -fPIC -Xcompiler -fno-strict-aliasing arch=compute_75,code=sm_75 --expt-extended-lambda -Xcompiler -fopenmp --expt-relaxed-constexpr`

Note the misplacement of -gencode. This results in a compiler error.
[This](https://github.com/lehner/gpt/blob/63ad008c58a034d5ce31fab8be3f3a4b0fc8709e/configure.ac#L155) looks suspicious.

Possible work-around: Replace any -Xcompiler by --compiler-options. This has not been tested yet, as it requires changes to grid configure.ac.

**Comment by pjgeorg** [comment]
@ssolbUR Comments?

**Comment by ssolbUR** [comment]
Hi,

just posted a pull request. Moving AC_PROG_CXX to the end of configure.ac should fix it.
Please verify.

best wishes,
Stefan

-- 
Dr. Stefan Solbrig
Universität Regensburg, Fakultät für Physik,
93040 Regensburg, Germany
Tel +49-941-943-2097

**Comment by pjgeorg** [comment]
What's the difference between your PR #73 and the PR #71 to fix issue #54 ?

PR #71 has been tested, it does fix #54, but not the issue described here.

I just realized my description was misleading.

I set CXXFLAGS when compiling grid. For compiling cgpt I do not explicitly set CXXFLAGS.
I.e. autotools should detect the correct CXXFLAGS via `grid-config --cxxflags`.
These are actually not saved in the variable CXXFLAGS, but GRID_CXXFLAGS. The GRID_CXXFLAGS are than later passed to the compiler [here](https://github.com/lehner/gpt/blob/63ad008c58a034d5ce31fab8be3f3a4b0fc8709e/lib/cgpt/Makefile.am#L39). Looking at this line it seems that CXXFLAGS are actually ignored?

**Comment by ssolbUR** [comment]
Hi,

Sorry, my bad.   PR #73 and PR #71 fix the same thing.
The important thing is, that AC_PROG_CXX comes after setting CXX.

I deliberately do    : ${CXXFLAGS=""}   before AC_PROG_CXX
why?  autoconf will set CXXFLAGS=-g   is the variable is not set.
Not all compilers (e.g., nvidia) understand -g

Alternatively, we can remove : ${CXXFLAGS=""}   before AC_PROG_CXX  this requiring users to do
configure  CXXFLAGS=<someting sensible> 
for compilers that don't understand -g

The question is:  should the user be able to pass additional values to CXXFLAGS?
Then we should define something like EXTRA_CXXFLAGS  and pass it to lib/cgpt/Makefile.am
Should these be prepended or appended to GRID_CXXFLAGS or overwrite it?

best wishes,
Stefan

-- 
Dr. Stefan Solbrig
Universität Regensburg, Fakultät für Physik,
93040 Regensburg, Germany
Tel +49-941-943-2097

**Comment by pjgeorg** [comment]
We can change how to handle user provided CXXFLAGS. I'm totally fine with the current solution.
Changing this behavior has nothing to do with this issue. Here we are talking about proper grid-config --cxxflags:
`-O3 -ccbin g++ -gencode arch=compute_75,code=sm_75 -Xcompiler -fPIC -Xcompiler -fno-strict-aliasing --expt-extended-lambda --expt-relaxed-constexpr -Xcompiler -fopenmp`
being somehow mangled on their way to the compiler, ending up there as:
`-O3 -ccbin g++ -gencode -Xcompiler -fPIC -Xcompiler -fno-strict-aliasing arch=compute_75,code=sm_75 --expt-extended-lambda -Xcompiler -fopenmp --expt-relaxed-constexpr`

This is the important part of the output trying to compile with nvcc:

> /bin/sh ../../libtool  --tag=CXX   --mode=compile nvcc -x cu -DHAVE_CONFIG_H -I. -I/glurch/scratch/lec17310/gpt-ci/x86/cuda/src/gpt/9ff99a1d/lib/cgpt -I../..  -I/usr/include/python3.6m  -I/glurch/scratch/lec17310/gpt-ci/x86/cuda/grid/gcc/none/80fd6ab4/include -I/usr/lib64/python3.6/site-packages/numpy/core/include  -I/usr/include/python3.6m -O3 -ccbin g++ -gencode arch=compute_75,code=sm_75 -Xcompiler -Xcompiler -Xcompiler -fPIC -Xcompiler -Xcompiler -Xcompiler -fno-strict-aliasing --expt-extended-lambda --expt-relaxed-constexpr -Xcompiler -Xcompiler -Xcompiler -fopenmp  -c -o lib/cgpt_la-munge.lo `test -f 'lib/munge.cc' || echo '/glurch/scratch/lec17310/gpt-ci/x86/cuda/src/gpt/9ff99a1d/lib/cgpt/'`lib/munge.cc
libtool: compile:  nvcc -x cu -DHAVE_CONFIG_H -I. -I/glurch/scratch/lec17310/gpt-ci/x86/cuda/src/gpt/9ff99a1d/lib/cgpt -I../.. -I/usr/include/python3.6m -I/glurch/scratch/lec17310/gpt-ci/x86/cuda/grid/gcc/none/80fd6ab4/include -I/usr/lib64/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -O3 -ccbin g++ -gencode -Xcompiler -fPIC -Xcompiler -fno-strict-aliasing arch=compute_75,code=sm_75 --expt-extended-lambda -Xcompiler -fopenmp --expt-relaxed-constexpr -c /glurch/scratch/lec17310/gpt-ci/x86/cuda/src/gpt/9ff99a1d/lib/cgpt/lib/munge.cc  -o lib/.libs/cgpt_la-munge.o

So I tried to follow what's happening to the flags:
configure stores in GRID_CXXFLAGS:
`-O3 -ccbin g++ -gencode arch=compute_75,code=sm_75 -Xcompiler -fPIC -Xcompiler -fno-strict-aliasing --expt-extended-lambda --expt-relaxed-constexpr -Xcompiler -fopenmp`

configure `fiXXer` turns this into:
`-O3 -ccbin g++ -gencode arch=compute_75,code=sm_75 -Xcompiler -Xcompiler -Xcompiler -fPIC -Xcompiler -Xcompiler -Xcompiler -fno-strict-aliasing --expt-extended-lambda --expt-relaxed-constexpr -Xcompiler -Xcompiler -Xcompiler -fopenmp`

Seems it is required to add all these -Xcompiler to make libtool not fuck up.

This is then passed to libtool, which then invokes the compiler with these options:
`-O3 -ccbin g++ -gencode -Xcompiler -fPIC -Xcompiler -fno-strict-aliasing arch=compute_75,code=sm_75 --expt-extended-lambda -Xcompiler -fopenmp --expt-relaxed-constexpr`

So it actually turns out it is not an issue in the configure.ac (or any related file), but once again libtool fucks up.
I have no clue how to tell libtool to just leave the `-gencode arch=compute_75,code=sm_75` as is and not mess it up.

Workaround for now:
Replace `-gencode arch=compute_75,code=sm_75` by `--gpu-architecture=compute_75 --gpu-code=sm_75`.
Note the `=` sign. It turns out libtool is too stupid to properly pass arguments of the form `--parameter_name <specification>`.

However, this is no solution as you probably won't be able to tell all users to not use this form of proper argument specification. Especially as `-gencode arch=compute_75,code=sm_75` seems to be the commonly used way to specify a target for nvcc.

Can we somehow get rid of libtool? So far it only caused issues.

**Comment by ssolbUR** [comment]
Hi,

The reason why the fiXXer exists is the following:  both nvcc and libtool have -Xcompiler and -Xlinker flags. Therefore, they need to be escaped by -Xcompiler resp. -Xlinker.

Can we get rid of libtool? Possibly yes, but it's likely to cause bugs on other occasions. Reasons for libtool is to make building of shared libs/modules easy.  Otherwise, one has to take care of each platform and figure out the extra compiler flags (-fPIC or -shared  or whatever) to build a shared lib.

I added a FiXXXer (better than FiXXer) that might resolve the problem. Anybody likes to test it?

best wishes,
Stefan

**Comment by pjgeorg** [comment]
I haven't check your new FiXXXer yet @ssolbUR.

Just wanted to let you know that even with all fixes posted previously applied, we still have at least one issue compiling cgpt with nvcc:
The compilation works fine now, however the linking fails due to libtool adding the option `-nostdlib`, which nvcc does not know.
Command executed by libtool: `libtool: link: nvcc -x cu  -shared -nostdlib  [...]`
Full error message: `nvcc fatal   : Unknown option 'nostdlib'`

Also note here, that libtool uses CXX (`nvcc -x cu`) for linking, not CXXLD (`nvcc -link`).
The error might actually be related to this.
How to tell libtool to use CXXLD to link?

**Comment by ssolbUR** [comment]
Hi,

As far as I can tell from the makefiles, libtool uses CXXLD.
But not all grid version provide this.  And if grid-config does not output a CXXLD, then we use by default CXX as a linker. (Which leads to an error for nvcc, because it doesn't like the -x cu option when linking.)

No idea how to get rid of -nostdlib.  Is hardcoded into libtool.


best wishes,
Stefan

-- 
Dr. Stefan Solbrig
Universität Regensburg, Fakultät für Physik,
93040 Regensburg, Germany
Tel +49-941-943-2097

**Comment by pjgeorg** [comment]
> But not all grid version provide this.  And if grid-config does not output a CXXLD, then we use by default CXX as a linker. (Which leads to an error for nvcc, because it doesn't like the -x cu option when linking.)

In my case CXXLD ist set correctly set (`nvcc -x link`, provided by grid-config --cxxld) correctly. I even double checked. Libtool just ignores it.

**Comment by philippscior** [comment]
So, how does this

> Workaround for now:
>Replace -gencode arch=compute_75,code=sm_75 by --gpu-architecture=compute_75 --gpu-code=sm_75.
> Note the = sign. It turns out libtool is too stupid to properly pass arguments of the form --parameter_name <specification>.

work? I wanted to try gpt on summit but can not get it to compile. 

Do I have to adjust the CXX arguments when compiling grid, or do I need to change something in GPT?

**Comment by pjgeorg** [comment]
> Do I have to adjust the CXX arguments when compiling grid, or do I need to change something in GPT?
Yes, you have to adjust your CXXFLAGS variable used to compile grid. Of course only in case you are currently using the `-gencode arch=compute_75,code=sm_75` syntax.

Reminder: With this change I'm able to compile (c)gpt, however linking still fails.

For now it's probably better to use the make script in lib/cgpt. There is even one for summit in particular (make.summit).

**Comment by DanielRichtmann** [comment]
To spare you trouble regarding the last sentence in the previous comment: Have a look at https://github.com/lehner/gpt/pull/70 before using `make.summit`.

**Comment by lehner** [comment]
As per gpt meeting discussions, no longer relevant
