### ISSUE TITLE
site-local inversion of color-spin matrices

### ISSUE THREAD

**Issue by krox** [lehner/gpt#77]
The inversion of site-local operators (`gpt.matrix.inv()`) is currently only implemented for color-matrices. It is not implemented for combined spin-color matrices, which is (at least for me) the main usecase (as part of preconditioning for a fermion solver).

On a side note: My previous python/numpy implementation did support everything (see here: https://github.com/lehner/gpt/pull/58/commits/da9fe28112641d4ba15607ec276797243baf0f38). I hope someone familiar with the new C++/Eigen implementation is willing to implement that usecase.

**Comment by DanielRichtmann** [comment]
I already have this exact code. I wanted to bring it upstream as part of my next PR, which I hope to put online shortly.

**Comment by krox** [comment]
Very cool. Thanks Daniel :) (for the meantime I keep using my python code, so its not critical for me.)

**Comment by lehner** [comment]
All we need is to add template specifications in https://github.com/lehner/gpt/blob/master/lib/cgpt/lib/foundation/matrix.h for color and spincolor matrices.  Daniel, I assume this is what you will do in your PR?

**Comment by DanielRichtmann** [comment]
Yes, see https://github.com/lehner/gpt/pull/78. These were actually the first commits of the other PR so it was easy to put them into a separate one already now.

**Comment by lehner** [comment]
This is now completed in the last few commits, where I also generalized the interface so that we can quickly add other functions.  I also took the time to complete the multiplication table (mcomplex * mcomplex) and such.
