### ISSUE TITLE
Compiling with hip on AMD

### ISSUE THREAD

**Issue by philomat** [lehner/gpt#87]
As Christoph suggested in the last meeting, I tried compiling with hip after I pulled a new commit:

`commit 16636b92fec8f8e5befd87e75976b6a7884219c7
Author: Christoph Lehner <christoph@lhnr.de>
Date:   Thu Mar 11 19:05:06 2021 +0100
`

Unfortunately, I still get the error:

`In file included from lib/basis.cc:19:
In file included from lib/lib.h:34:
In file included from lib/foundation.h:60:
lib/foundation/basis.h:180:36: error: reference to __host__ function 'operator[]' in __host__ __device__ function
        B += Qt_j[k + vec_i*n_elements] * left_basis_v[left_index*n_virtual + virtual_i](ss) * right_basis_v[right_index*n_virtual + virtual_i](ss);
                                          ^
/home/scior/gpt/dependencies/Grid/Grid/threads/Accelerator.h:339:5: note: called by 'LambdaApply<(lambda at lib/foundation/basis.h:162:3)>'
    Lambda(x,y,z);
    ^
/usr/lib/gcc/x86_64-redhat-linux/8/../../../../include/c++/8/bits/stl_vector.h:930:7: note: 'operator[]' declared here
      operator[](size_type __n) _GLIBCXX_NOEXCEPT
      ^
`
when I try to compile.

**Comment by lehner** [comment]
The commit in question is not yet pushed to github, I will let you know.
